baseURL = "https://wartimefriends.org/"
# languageCode = "en-us"
# languageCode = "it-it"
defaultContentLanguage = "it"
# theme = "hugo-initio"
title = "Wartime Friends"

[Languages]

[Languages.it]
title = "Associazione Culturale \"Wartime Friends\""
weight = 1
[Languages.it.params]
linkedin = "italiano"
[Languages.it.navigation]
help  = "Aiuto"


[Languages.en]
title = "Cultural Association Wartime Friends"
weight = 2
[Languages.en.params]
linkedin = "english-link"



[params]
    name = "Wartime Friends"
    description = "Associazione Culturale Wartime Friends"
    email = "info@wartimefriends.org"
#   phone = "+234 23 9873237"
#   address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2017
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = false
    showRecentWorks = true
    showDownload = true
    showClients = false


[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

# [params.google.analytics]
#     trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/Wartimefriends-165894540102395"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
# [[params.social]]
# 	title = "twitter"
# 	url = "https://twitter.com/nickname"
#     icon = "fa-twitter-square"
#     footer = true
#     sharethis = true
#     network = "twitter"
# [[params.social]]
# 	title = "instagram"
# 	url = "https://www.instagram.com/nickname"
#     icon = "fa-instagram"
#     footer = true
#     sharethis = false
#     network = ""
# [[params.social]]
# 	title = "google+"
# 	url = "https://plus.google.com/+nickname"
#     icon = "fa-google-plus-square"
#     footer = false
#     sharethis = true
#     network = "googleplus"
# [[params.social]]
# 	title = "linkedin"
# 	url = "https://www.linkedin.com/in/nickname"
#     icon = "fa-linkedin-square"
#     footer = false
#     sharethis = true
#     network = "linkedin"
# [[params.social]]
# 	title = "tumblr"
# 	url = "https://nickname.tumblr.com"
#     icon = "fa-tumblr-square"
#     footer = false
#     sharethis = false
#     network = "tumblr"
# [[params.social]]
# 	title = "github"
# 	url = "https://github.com/nickname"
#     icon = "fa-github"
#     footer = true
#     sharethis = false
#     network = ""
[[params.social]]
	title = "email"
	url = "mailto:info@wartimefriends.org"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
