# baseURL = "https://wartimefriends.org/"
baseURL = "https://wartimefriends.netlify.com/"
# relativeurls = true
# languageCode = "en-us"
# languageCode = "it-it"
defaultContentLanguage = "it"
# theme = "hugo-initio"
title = "Wartime Friends"

[languages]

[languages.it]
title = "Associazione Culturale \"Wartime Friends\""
weight = 1

[languages.it.navigation]
help  = "Aiuto"


[languages.en]
title = "Cultural Association Wartime Friends"
weight = 2


[params]
    name = "Wartime Friends"
    description = "Associazione Culturale Wartime Friends"
    email = "info@wartimefriends.org"
#   phone = "+234 23 9873237"
#   address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2017
    background = ""
    DateForm = "January 2, 2006"
    favicon = "images/gt_favicon.png"

    showSubheader = true
    showServices = false
    showRecentWorks = true
    showDownload = true
    showClients = false




[[languages.it.menu.main]]
    name = "inizio"
    url = "/"
    weight = 1
[[languages.it.menu.main]]
    name = "chi siamo"
    url = "/about/"
    weight = 2
[[languages.it.menu.main]]
    name = "storia"
    url = "/history/"
    weight = 3
[[languages.it.menu.main]]
    name = "amici"
    url = "/friends/"
    weight = 4
[[languages.it.menu.main]]
    name = "ricerche"
    url = "/research/"
    weight = 6
[[languages.it.menu.main]]
    name = "mostre"
    url = "/exhibitions/"
    weight = 7
[[languages.it.menu.main]]
    name = "cimiteri di guerra"
    url = "/cemeteries/"
    weight = 8



[[languages.en.menu.main]]
    name = "home"
    url = "/en/"
    weight = 1
[[languages.en.menu.main]]
    name = "about us"
    url = "/en/about/"
    weight = 2
[[languages.en.menu.main]]
    name = "history"
    url = "/en/history/"
    weight = 3
[[languages.en.menu.main]]
    name = "friends"
    url = "/en/friends/"
    weight = 4
[[languages.en.menu.main]]
    name = "research"
    url = "/en/research/"
    weight = 6
[[languages.en.menu.main]]
    name = "exhibitions"
    url = "/en/exhibitions/"
    weight = 7
[[languages.en.menu.main]]
    name = "war cemeteries"
    url = "/en/cemeteries/"
    weight = 8



# [[menu.main]]
#     name = "blog"
#     url = "/post/"
#     weight = 5




# [params.disqus]
#     site = "hugo-initio-site.disqus.com"

# [params.sharethis]
#     property = "123456789012345678901234"
#     custom = true

# [params.google.analytics]
#     trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/Wartimefriends-165894540102395"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
# [[params.social]]
# 	title = "twitter"
# 	url = "https://twitter.com/nickname"
#     icon = "fa-twitter-square"
#     footer = true
#     sharethis = true
#     network = "twitter"
# [[params.social]]
# 	title = "instagram"
# 	url = "https://www.instagram.com/nickname"
#     icon = "fa-instagram"
#     footer = true
#     sharethis = false
#     network = ""
# [[params.social]]
# 	title = "google+"
# 	url = "https://plus.google.com/+nickname"
#     icon = "fa-google-plus-square"
#     footer = false
#     sharethis = true
#     network = "googleplus"
# [[params.social]]
# 	title = "linkedin"
# 	url = "https://www.linkedin.com/in/nickname"
#     icon = "fa-linkedin-square"
#     footer = false
#     sharethis = true
#     network = "linkedin"
# [[params.social]]
# 	title = "tumblr"
# 	url = "https://nickname.tumblr.com"
#     icon = "fa-tumblr-square"
#     footer = false
#     sharethis = false
#     network = "tumblr"
# [[params.social]]
# 	title = "github"
# 	url = "https://github.com/nickname"
#     icon = "fa-github"
#     footer = true
#     sharethis = false
#     network = ""
[[params.social]]
	title = "email"
	url = "mailto:info@wartimefriends.org"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
