[context.production.environment]
  HUGO_VERSION = "0.55.6"

[build]
  command = "hugo"
  publish = "public"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.6"